"""empty message

Revision ID: 21e36ce51152
Revises: 4ea9aaada5f9
Create Date: 2022-02-15 11:53:23.118796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e36ce51152'
down_revision = '4ea9aaada5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('passwordcifrada', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'passwordcifrada')
    # ### end Alembic commands ###
