"""empty message

Revision ID: 36c35e5b5884
Revises: 21e36ce51152
Create Date: 2022-02-15 11:54:38.396847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36c35e5b5884'
down_revision = '21e36ce51152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'passwordcifrada',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'passwordcifrada',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('usuario', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
